version: "3"

services:
  bitcoind:
    build: ./docker/bitcoin
    #ports:
    #  - 18332:18332
    volumes:
      - $HOME/cyphernode/bitcoin/:/data/.bitcoin
    networks:
      - back
    restart: always

  postgres:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - back
    restart: always

  bitcoind-zmq:
    build: ./back/bitcoind-zmq
    environment:
      HASURA_SCHEMA_URL: http://graphql-engine:8080/v1/graphql
      HASURA_PASS: secretkey
      ZMQ_HASHBLOCK: tcp://bitcoind:3000
      ZMQ_RAWBLOCK: tcp://bitcoind:3001
      # ZMQ_RAWTX: tcp://bitcoind:3002
      # ZMQ_HASHTX: tcp://bitcoind:3003
    depends_on:
      - "bitcoind"
      - "postgres"
      - "graphql-engine"
    networks:
      - back
    restart: always

  bitcoind-rpc:
    build: ./back/bitcoind-rpc
    volumes:
      - $HOME/cyphernode/bitcoin/testnet3/.cookie:/data/.bitcoin/testnet3/.cookie
    environment:
      # BITCOIND_RPC_PORT: 18443 #regtest
      BITCOIND_RPC_PORT: 18332 #testnet
      BITCOIND_RPC_HOST: 'bitcoind'
      BITCOIND_RPC_COOKIE: '/data/.bitcoin/testnet3/.cookie'
    depends_on:
      - "bitcoind"
      - "postgres"
    networks:
      - back
    restart: always

  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "bitcoind-rpc"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: secretkey
      BITCOIND_RPC_ENDPOINT: http://bitcoind-rpc:9000/
    networks:
      - back
    restart: always

  bitcoin-electrs:
    build: ./docker/bitcoind-electrs
    entrypoint:
      - electrs
    command:
      - -vvvv
      - --daemon-dir
      - /home/user/.bitcoin
      - --daemon-rpc-addr
      - bitcoind:18332
      - --network
      - testnet
      - --db-dir
      - .bitcoin/.electrs/db
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --txid-limit
      - "1000"
    volumes:
      - $HOME/cyphernode/bitcoin/:/home/user/.bitcoin
    depends_on:
      - "bitcoind"
    networks:
      - back
    restart: always

  bitcoind-electrs-rpc:
    build: ./back/bitcoind-electrs-rpc
    depends_on:
      - "bitcoind"
      - "bitcoin-electrs"
    environment:
      HASURA_SCHEMA_URL: http://graphql-engine:8080/v1/graphql
      HASURA_PASS: secretkey
      ELECTRS_RPC_ENDPOINT: http://bitcoind-electrs-rpc:9001/
    networks:
      - back
    restart: always

  # bitcoind-zmq-front:
  #  build: ./front/bitcoind-zmq
  #  ports:
  #    - "3001:3001"
  #  depends_on:
  #    - "bitcoind"
  #    - "postgres"
  #    - "graphql-engine"
  #  networks:
  #    - front
  #  restart: always

volumes:
  db_data:

networks:
  back:
    external: true
  front:
    external: true
